name: Node.js CICD


on:
    push: 
        branches: [ main ]
    
jobs:
    build:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
                node-version: ${{ matrix.node-version }}
        - run: |
            cd Backend
            npm i
            cd Frontend
            npm i
            npm run build