# name: Fullstack CICD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14' # Specify your desired Node.js version

#       - name: Install Backend Dependencies
#         run: |
#           cd Backend
#           npm install

#       - name: Install Frontend Dependencies
#         run: |
#           cd Frontend
#           npm install



#       - name: Build Frontend
#         run: |
#           cd Frontend
#           npm run build

      # Deployment steps (e.g., to a hosting service like Azure, AWS, etc.)
      # - name: Deploy Backend to Hosting Service
      #   run: |
      #     # Add backend deployment steps here
      #     # Example: Deploy to Azure, AWS, etc.

      # - name: Deploy Frontend to Hosting Service
      #   run: |
      #     # Add frontend deployment steps here
      #     # Example: Deploy to Azure, AWS, etc.



name: Node.js CICD


on:
    push: 
        branches: [ main ]
    
jobs:
     build-and-deploy:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
                node-version: ${{ matrix.node-version }}
        - run: |
            cd Backend
            npm i
            cd Frontend
            npm i
            npm run build