name: Deployment From Github To AWS
on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v2
        with:
          path: Backend # Checkout the backend into 'backend' directory

      - name: Generate Backend Deployment Package
        run: |
          cd Backend
          zip -r backend-deploy.zip * -x "*node_modules*"
         
        working-directory: ./Backend

      - name: Deploy Backend to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: devops-backend
          environment_name: Devops-backend-env  
          version_label: "backend-${{ github.sha }}"
          region: eu-north-1
          deployment_package: ./Backend/backend-deploy.zip

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v2
        with:
          path: Frontend # Checkout the frontend into 'frontend' directory

      - name: Generate Frontend Deployment Package
        run: |
          cd Frontend
          zip -r frontend-deploy.zip * -x "*node_modules*"
        working-directory: ./Frontend

      - name: Deploy Frontend to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: devops-frontend
          environment_name: Devops-frontend-env    
          version_label: "frontend-${{ github.sha }}"
          region: eu-north-1
          deployment_package: ./Frontend/frontend-deploy.zip
